os:
    - linux
    - osx

dist: bionic # trusty
sudo: false

language: cpp
compiler: gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-8
            - gcc-8
            - cmake

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew install cmake;
      brew upgrade cmake;
    fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export CC=gcc-7;
      export CXX=g++-7;
    fi

script:
    - cd example
    - mkdir build
    - cd build

    - export CXX=/usr/bin/g++-8
    - export CC=/usr/bin/gcc-8
    - ln -s $CXX /usr/bin/g++
    - ln -s $CC /usr/bin/gcc

    - $CXX -v
    - $CC -v
    - cmake --version

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        export COVERAGE_FLAGS='-D ENABLE_COVERAGE:BOOL=TRUE';
    fi

    - cmake $(python ./../script/cmake_release_flags.py) $COVERAGE_FLAGS ..
    - cmake --build . -- -j2

    - ctest -j2

    - bash <(curl -s https://codecov.io/bash)
