dist: trusty
sudo: false
language: cpp

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-8

script:
    - cd example
    - CXX=/usr/bin/g++-8 CC=/usr/bin/gcc-8
    - cmake $(python ./script/cmake_release_flags.py) .
    - cmake --build . -- -j2
