image:
    - Visual Studio 2017

# clone_folder: c:\project\source

before_build:
    - cd example
    - mkdir build

build_script:
    - cd build
    - CXX=/usr/bin/g++-8 CC=/usr/bin/gcc-8
    - cmake $(python ./script/cmake_release_flags.py) -G "Visual Studio 15" ..
    - cmake --build .
